export interface RoomListItem {
  id: number
  roomId: string
  name: string | null
  status: 'active' | 'closed'
  requireApproval: boolean
  maxViewers: number
  hasPassword: boolean
  viewerCount: number
  sharerOnline: boolean
  mode: 'screen-share' | 'watch-together'
  lastAccessedAt: string
  createdAt: string
}

/** Room IDs are generated by the server. Only reject an empty entry here;
 * unknown IDs must reach the existing join flow so it can report the error. */
export function roomPath(input: string): string | null {
  const roomId = input.trim()
  return roomId ? `/room/${encodeURIComponent(roomId)}` : null
}

export function featuredRooms(rooms: RoomListItem[]): RoomListItem[] {
  return rooms
    .filter((room) => room.status === 'active')
    .sort(
      (a, b) =>
        (Date.parse(b.lastAccessedAt) || 0) -
        (Date.parse(a.lastAccessedAt) || 0)
    )
    .slice(0, 3)
}
